name: continuous-deployment

permissions: write-all
on:
    push:
        tags:
            - '*'
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install Python
            
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                versions: 1.1.13
                virtualenvs-create: true
                virtualenvs-in-project: true

            - name: Install dependencies
              run: |
                poetry install -C python-artifact-signer

            - name: Build Poetry
              run: |
                cd python-artifact-signer/
                poetry build
                cd ..

            - name: Upload Poetry Build
              uses: actions/upload-artifact@v4
              with:
                name: poetry-build
                path: python-artifact-signer/dist/*

            - name: Generate SBOM
              run: |
                source python-artifact-signer/.venv/bin/activate
                cyclonedx-py poetry -o sbom.json python-artifact-signer

            - name: Attest SBOM
              uses: actions/attest-sbom@v1
              with:
                subject-path: python-artifact-signer/dist/
                sbom-path: sbom.json
                github-token: ${{ github.token }}
                
            - name: Upload SBOM
              uses: actions/upload-artifact@v4
              with:
                name: sbom
                path: sbom.json

            - name: Upload Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    python-artifact-signer/dist/*
