name: continuous-integration
on: [push]
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Install Python
            
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                versions: 1.1.13
                virtualenvs-create: true
                virtualenvs-in-project: true
            
            - name: Install dependencies
              run: |
                poetry install -C python-artifact-signer

            - name: Run Black
              run: |
                source python-artifact-signer/.venv/bin/activate
                black --check python-artifact-signer/python_artifact_signer

            - name: Run ruff
              run: |
                source python-artifact-signer/.venv/bin/activate
                ruff check python-artifact-signer/python_artifact_signer

            - name: Run Bandit
              run: |
                source python-artifact-signer/.venv/bin/activate
                bandit -r python-artifact-signer/python_artifact_signer

            - name: Run TruffleHog
              uses: trufflesecurity/trufflehog@main
              with:
                path: .
                extra_args:
                  --since-commit HEAD --no-verification --fail --no-update
            
            - name: Run Pytest
              run: |
                source python-artifact-signer/.venv/bin/activate
                PYTHONPATH=python-artifact-signer/ pytest --cov
              

