name: continuous-integration
on: [push]
jobs:
    ci:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Install Python
            
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                versions: 1.1.13
                virtualenvs-create: true
                virtualenvs-in-project: false

            - name: Set up cache
              uses: actions/cache@v4
              id: cached-poetry-dependencies
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
            
            - name: Install dependencies
              run: |
                poetry install -C python-artifact-signer

            - name: Run Black
              run: |
                python-artifact-signer/.venv/bin/black --check python-artifact-signer/python_artifact_signer

            - name: Run ruff
              run: |
                python-artifact-signer/.venv/bin/ruff check python-artifact-signer/python_artifact_signer

            - name: Run Bandit
              run: |
                python-artifact-signer/.venv/bin/bandit -r python-artifact-signer/python_artifact_signer

            # - name: Run TruffleHog
            #   uses: trufflesecurity/trufflehog-actions-scan@v2
            #   with:
            #     scan-directory: './'
            #     github-token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Run Pytest
              run: |
                PYTHONPATH=python-artifact-signer/ .venv/bin/pytest --cov
              

