name: continuous-integration
on: [push]
jobs:
    ci:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Install Python
            
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            
            - name: Install Poetry
              run: |
                python -m pip install poetry

            - name: Configure poetry
              run: |
                python -m poetry config virtualenvs.in-project true
            
            - name: Cache the virtualenv
              uses: actions/cache@v2
              with:
                path: ./.venv
                key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              run: |
                cd python-artifact-signer
                poetry install --no-interaction --no-root
                cd ..

            - name: Run Black
              run: |
                black --check python-artifact-signer/python_artifact_signer

            - name: Run ruff
              run: |
                ruff check python-artifact-signer/python_artifact_signer

            - name: Run Bandit
              run: |
                bandit -r python-artifact-signer/python_artifact_signer

            # - name: Run TruffleHog
            #   uses: trufflesecurity/trufflehog-actions-scan@v2
            #   with:
            #     scan-directory: './'
            #     github-token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Run Pytest
              run: |
                PYTHONPATH=python-artifact-signer/ pytest --cov
              

