name: continuous-integration
on: [push]
jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

  install-poetry:
    runs-on: ubuntu-latest
    needs: install-python
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          versions: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

  install-dependencies:
    runs-on: ubuntu-latest
    needs: install-poetry
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          versions: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install -C python-artifact-signer

  run-black:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          source python-artifact-signer/.venv/bin/activate
          black --check python-artifact-signer/python_artifact_signer

  run-ruff:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          source python-artifact-signer/.venv/bin/activate
          ruff check python-artifact-signer/python_artifact_signer

  run-bandit:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          source python-artifact-signer/.venv/bin/activate
          bandit -r python-artifact-signer/python_artifact_signer

  run-pytest:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          source python-artifact-signer/.venv/bin/activate
          PYTHONPATH=python-artifact-signer/ pytest --cov
